#!/usr/bin/env bash
# Installs the "cka" command system-wide so it can be run from anywhere,
# right after cloning this repo (e.g. on a fresh Killercoda node).
#
# Usage:
#   ./install.sh
#
# After this, you can run from any directory:
#   cka 1        -> runs scripts/run-question.sh 1
#   cka finish   -> runs scripts/finish-test.sh

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET="/usr/bin/cka"

chmod +x "$REPO_ROOT/scripts/run-question.sh" "$REPO_ROOT/scripts/finish-test.sh" "$REPO_ROOT/scripts/show-timer.sh" 2>/dev/null || true

# /usr/bin is usually only writable by root. Killercoda sessions normally
# run as root already; locally, re-run this script with sudo if needed.
SUDO=""
if [[ ! -w "$(dirname "$TARGET")" ]]; then
  if command -v sudo >/dev/null 2>&1; then
    SUDO="sudo"
  else
    echo "Error: $(dirname "$TARGET") is not writable and 'sudo' is not available. Re-run as root." >&2
    exit 1
  fi
fi

$SUDO bash -c "cat > '$TARGET'" <<EOF
#!/usr/bin/env bash
# Auto-generated by install.sh - do not edit directly.
REPO_ROOT="$REPO_ROOT"

if [[ "\$1" == "finish" ]]; then
  shift
  exec "\$REPO_ROOT/scripts/finish-test.sh" "\$@"
else
  exec "\$REPO_ROOT/scripts/run-question.sh" "\$@"
fi
EOF

chmod +x "$TARGET"

echo "==> 'cka' command installed at $TARGET"
echo "    Usage: cka <question-number>   (e.g. cka 1)"
echo "           cka finish              (ends the test and shows the score)"
